services:
  chat-ui:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SUPABASE_URL=${SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_OLLAMA_URL=${NEXT_PUBLIC_OLLAMA_URL}
        - NEXT_PUBLIC_USER_FILE_SIZE_LIMIT=${NEXT_PUBLIC_USER_FILE_SIZE_LIMIT}
    container_name: chat-ui
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
