[phases.setup]
providers = ["nodejs_20"]

[phases.install] 
cmds = [
  "npm ci --legacy-peer-deps --prefer-offline"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start -- --hostname 0.0.0.0 --port 3000"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0" 
PORT = "3000"
NPM_CONFIG_CACHE = "/tmp/.npm"
NEXT_TELEMETRY_DISABLED = "1"